### PR TITLE
feat(fixtures): fixtures data for suppliers

### PR DESCRIPTION
**Pull request by MyuddinKhatri**
Issue - https://github.com/agritheory/test_utils/issues/10
Collected fixtures data for suppliers and addresses from beam, check_run, inventory_tools and electronic_payments(included Tax Authority as supplier)

Collected fixtures data for Payment Terms Template from autoreader, check_run and electronic_payments

### CODE REVIEW

**Comment by MyuddinKhatri** [comment]
@agritheory default price list in inventory_tools for suppliers is "Bakery Buying". In this PR setting default price list as "Standard Buying" for suppliers.

**Comment by agritheory** [comment]
@MyuddinKhatri Marking as draft until we stabilize the "shortlist" / "create_only" API

**Comment by MyuddinKhatri** [comment]
> @MyuddinKhatri Marking as draft until we stabilize the "shortlist" / "create_only" API

Yes, once we finalize the approach and merge Item fixtures PR, then we can follow same for the others.

**Comment by MyuddinKhatri** [comment]
@agritheory updated fixtures for suppliers, added fixtures for addresses and payment terms template.

**Review by Alchez — APPROVED** [review]

**Comment by agritheory** [comment]
@MyuddinKhatri Can you rebase this to fix the pre-commit spelling issue?

**Pull request merged**
